
name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: shelterapp-scrapers # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.8'                 # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-n-test-n-deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest        
    environment:                        # The environment this job references
      name: CI
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master 
      
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
                
    - name: 'Resolve Project Dependencies Using Pip'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      env:
        DBUSERNAME: ${{ secrets.DBUSERNAME }}
        PW: ${{ secrets.PW }}
      run: |
        pip install pytest
        pytest

    - name: 'Resolve Project Dependencies Using Pip for Azure'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1.1.8
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_NEW }}
